home :
  path : /
  method : get
  controller : app\controllers\WelcomeController
  action : index

welcome :
  path : /welcome
  method : get
  controller : app\controllers\WelcomeController
  action : index

adminIndex :
  path : /admin/welcome
  method : get
  controller : \admin\controllers\WelcomeController
  action : index

adminLogin :
  path : api/login
  method : get
  controller : \admin\controllers\UserAccountController
  action : index

getArticleList :
  path : api/get-article-list
  method : get
  controller : app\controllers\ArticleController
  action : getList

