welcome :
  path : /welcome
  method : get
  controller : app\controllers\WelcomeController
  action : index

adminIndex :
  path : /admin/welcome
  method : get
  controller : \admin\controllers\WelcomeController
  action : index
